Repository briandfoy/pod-perldoc, pull requests merged in 2023-12, with the labels that each got.

#47 Use `test -e` instead of `test -f`
  lib/Pod/Perldoc.pm
  lib/Pod/Perldoc/ToTerm.pm
Labels: Type: bug, Status: needs verification, Priority: high

#39 waitpid for the man process to exit
  lib/Pod/Perldoc/ToMan.pm
Labels: Type: bug, Status: needs verification, Priority: high

#40 Enable UTF-8 for ToMan if _is_mandoc
  lib/Pod/Perldoc/ToMan.pm
Labels: Type: enhancement, Status: stalled, Priority: low

#37 set $self->{output_to_stdout} to true if TERM environment variable ex…
  lib/Pod/Perldoc.pm
Labels: Type: bug, Status: needs verification, Priority: high

#58 Start better testing
  MANIFEST
  lib/Pod/Perldoc.pm
  lib/Pod/Perldoc/ToMan.pm
  t/02_module_pod_output.t
  t/02_url_pod_output.t
  t/lib/TestUtils.pm
Labels: Type: test bug, Status: accepted

#63 An issue template for bug reports
  .github/ISSUE_TEMPLATE/bug.md
Labels: Type: documentation

#66 Add util/perldoc-debug to collect debugging info
  .github/ISSUE_TEMPLATE/bug.md
  CONTRIBUTING
  util/perldoc-bug
Labels: Type: enhancement, Status: accepted, Priority: low

#67 Re-order a function in perldoc-bug to alphabetize
  util/perldoc-bug
Labels: Type: enhancement, Status: accepted

#68 Fix up some repo details for continued maintenance
  Makefile.PL
  lib/Pod/Perldoc.pm
  lib/Pod/Perldoc/BaseTo.pm
  lib/Pod/Perldoc/GetOptsOO.pm
  lib/Pod/Perldoc/ToANSI.pm
  lib/Pod/Perldoc/ToChecker.pm
  lib/Pod/Perldoc/ToMan.pm
  lib/Pod/Perldoc/ToNroff.pm
  lib/Pod/Perldoc/ToPod.pm
  lib/Pod/Perldoc/ToRtf.pm
  lib/Pod/Perldoc/ToText.pm
  lib/Pod/Perldoc/ToTk.pm
  lib/Pod/Perldoc/ToXml.pm
Labels: Status: accepted, Priority: low, Type: distribution housekeeping

#71 Update some email addresses (#69)
  Changes
  Makefile.PL
  lib/Pod/Perldoc.pm
  lib/Pod/Perldoc/BaseTo.pm
  lib/Pod/Perldoc/GetOptsOO.pm
  lib/Pod/Perldoc/ToANSI.pm
  lib/Pod/Perldoc/ToChecker.pm
  lib/Pod/Perldoc/ToMan.pm
  lib/Pod/Perldoc/ToNroff.pm
  lib/Pod/Perldoc/ToPod.pm
  lib/Pod/Perldoc/ToRtf.pm
  lib/Pod/Perldoc/ToTerm.pm
  lib/Pod/Perldoc/ToText.pm
  lib/Pod/Perldoc/ToTk.pm
  lib/Pod/Perldoc/ToXml.pm
  perldoc.pod
  util/perldoc-bug
Labels: Type: distribution housekeeping
